---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyverse)

```

```{r, warning=F}
multmerge = function(mypath){
  filenames=list.files(path=mypath, full.names=TRUE)
  datalist = (lapply(filenames, function(x){read.csv(file=x, colClasses=c("zip_code"="character"), na.strings=c(""))}))
  res <- Reduce(function(x,y){bind_rows(x, y)}, datalist)
  return(res)
}


```
```{r, warning=F}
all_gas_data <- multmerge("D:/Python/gasbuddyscrap/30_03_2020")
all_gas_data
```

```{r}

all_gas_data %>% 
  summary()


#unique(all_gas_data$last_update_time)

```

```{r}
data_with_price <- all_gas_data %>% 
  filter(!is.na(price))

data_with_price

```

```{r}

clean_data  <- data_with_price %>% 
  mutate(id_value=str_extract(id_value, pattern = "\\d+")) %>% 
   mutate(price=as.numeric(str_extract(price, pattern = "[+-]?([0-9]*[.])?[0-9]+"))) %>% 
  separate(city_state, c("city", "state_location"), sep = ",")

price_col <- clean_data$price
price_col[which(price_col>30)] <- price_col[price_col > 30] / 100


clean_data_new <- clean_data %>% 
  mutate(price = price_col)


clean_data_new



```
```{r}
#most popular gas station for gasbuddy users
 clean_data %>% 
   group_by(name) %>% 
   count(sort = T)
```
```{r}
clean_data_new %>% 
  group_by(state, city) %>% 
  summarise(avg_gas_price=mean(price, na.rm = T))
```
```{r}
clean_data_new %>% 
  filter(state=="FL", city=="Lakeland")
```


```{r}

#average gas prices from diffrerent states

state_name_data <- clean_data_new %>% 
  mutate(full_state=tolower(setNames(state.name, state.abb)[state])) %>% 
  group_by(full_state) %>% 
  summarise(price=mean(price))

state_name_data


p <- ggplot(state_name_data, aes(map_id = full_state)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = price), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  scale_fill_continuous(high = "#132B43", low = "#56B1F7")
p

```
https://github.com/wmurphyrd/fiftystater

```{r}


clean_data_new %>%
  ggplot() + geom_boxplot(aes(x=fct_reorder(as.factor(state), price, mean), y=price), alpha=0.5, outlier.shape = NA) +
  labs(x="States", y="Price ($)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 0, vjust = 0.5))




```


